Created homepage with text that says Hello Microverse
MesakDuduCoder/Hello-world pull request #1
Opened 2023-02-21 07:59 UTC by MesakDuduCoder

My first project at Microverse.

2023-02-21 08:19 UTC, IngDavidTM requested changes
## Hi @MesakDuduCoder  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 08:19 UTC, IngDavidTM commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] You did a fantastic job adding the `License` section to your README :+1:, but as a general requirement you should create a `LICENSE` file and link it in the README file because it would make your project looks professional. You can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

2023-02-21 08:19 UTC, IngDavidTM commented on README.md
> +<!-- AUTHORS -->
- [ ] While you did a fantastic job creating your README file :+1:, adding the required information to Setup is required. I think it would be better if you add the code that the user has to run to clone the repository

- Hint : 

```
git@github.com:MesakDuduCoder/Hello-world.git
```

2023-02-21 10:26 UTC, MesakDuduCoder commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
Hello @IngDavidTM I have resolved both change requests but I dont know how to proceed next should I ask for another review or can u verify my project for submission? p.s Thank you for the good reviews

2023-02-21 10:31 UTC, IngDavidTM commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
Hi @MesakDuduCoder, yes you have to ask for another review

2023-02-22 10:00 UTC, Shedrack-Sunday approved these changes
Hi @MesakDuduCoder 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)


# Highlights
- No linter errors ✔️
- Good implementations ✔️

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-22 10:21 UTC, merged